### ISSUE TITLE
初めてのWebアプリ制作_試行錯誤のメモ

### ISSUE THREAD

**Issue by nana1111111** [nana1111111/studyapp#1]
＜制作物目標＞[「学習時間管理アプリ」](https://docs.google.com/presentation/d/1SPolmudEkrg0Mc4Uqghdf-yZhoE24kNSO5qLhDEdSUo/edit#slide=id.p)

**Comment by nana1111111** [comment]
Sinatraで下記の順番で作成していこうと思って始めた。
※大事な機能から

---------------------------------------------
**1.日付・学習時間・メモ　をpostできるページ
2.postからデータベースに送信された情報を計算し表示するマイページ
3.Top画面と、ログイン・ログアウト機能
4.最後に見た目をCSSで整える**
---------------------------------------------

**Comment by nana1111111** [comment]
まずは、app.rbを作成。
・上部は後にログイン機能をいれることもあり、先にcookies、sessionのことも記載しておいた
・dbname => "study"　にした
・学習情報をgetして、erbにくるルーティング
・


app.rb

```
require 'sinatra'
require 'sinatra/reloader'
require 'sinatra/cookies'
require 'pg'

enable :sessions

client = PG::connect(
    :host => "localhost",
    :user => ENV.fetch("USER","naru"),:password => '',
    :dbname => "study")

get "/posts" do
    @posts = client.exec_params("SELECT * from posts").to_a
    return erb :posts
end

post '/posts' do
    date = params[:date]
    time = params[:time]
    content = params[:content]

    client.exec_params(
    "INSERT INTO posts (date, time, content) VALUES ($1, $2, $3)",
    [date, time, content]
    )
end
```

**Comment by nana1111111** [comment]
投稿フォームの見た目であるposts.erbを下記のように作成。
※CSSもどう挿入する記述を書いたらいいかイメージのため簡単に作り記載。
※背景色など変わった程度を確認。連携のさせ方がわかったので、CSSはまた最後。今は飛ばす。

posts.erb

```
<link rel="stylesheet" href="/css/study.css" type="text/css" > 

<form action="/posts" method="post">
    <div>
        <label for="date">日付: </label>
        <input type="date" date="date">
    </div>
    <div>
        <label for="time">勉強時間: </label>
        <input type="integer" time="time">
    </div>
    <div>
        <label for="memo">メモ: </label>
        <textarea name="content" cols=50 rows=10></textarea>
    </div>

    <input type="submit" value="記録">
</form>

<% @posts.each do |post| %>
    <h1><%= post['date'] %></h1>
    <p><%= post['time'] %></p>
    <p><%= post['content'] %></p>
<% end %>
```

**Comment by nana1111111** [comment]
データベースを作るため、ターミナルでPostgreSQLを起動〜データベース作成〜postsテーブルを作成したい！と思い、以下のコマンドを順番に実行。

psql
`CREATE DATABASE study;
`

**Comment by nana1111111** [comment]
データベースを作るため、ターミナルでPostgreSQLを起動〜データベース作成〜postsテーブルを作成したい！と思い、以下のコマンドを順番に実行。
※実行コマンドと、結果をそのままコピペ。

psql
```
postgres=# CREATE DATABASE study;
CREATE DATABASE
postgres=# \c study
You are now connected to database "study" as user "naru".
study=# CREATE TABLE posts (
study(# id SERIAL NOT NULL PRIMARY KEY ,
study(# date DATE NOT NULL ,
study(# time INTEGER NOT NULL ,
study(# content TEXT
study(# );
CREATE TABLE
```

**Comment by nana1111111** [comment]
ここでいったん、下記からフォーム送信するも、エラー。。積んでいる。。
[http://localhost:4567/posts](http://localhost:4567/posts)


**①最初のエラー：リレーションエラー**
→データベース名の指定がおかしいのか？という考えにたどりつきapp.rbを下記に修正。
`:dbname => ENV.fetch("DB_NAME", "study"))`　※最初例文通りの"myapp"のままだった。

**②次のエラー：nullだそう。。入力してるのにどうして・・・**
```
PG::NotNullViolation at /posts
ERROR: null value in column "date" violates not-null constraint DETAIL: Failing row contains (7, null, null, エラーをどうにかしたいです。).
```

psqlでpostテーブルはどうなっているか確認。0 rows・・・
```
study=# SELECT * FROM posts;
 id | date | time | content 
----+------+------+---------
(0 rows)

```


WHYYYYYYYYYYYYY

**Comment by HidetoNakasone** [comment]
> Failing row contains (7, null, null, エラーをどうにかしたいです。).
このエラーは、

```ruby
    client.exec_params(
    "INSERT INTO posts (date, time, content) VALUES ($1, $2, $3)",
    [date, time, content]
    )
```
この部分ですよね。

原因は、dateとtime変数の中身がnullと推測できます。

```ruby
    date = params[:date]
    time = params[:time]
```
この部分も特に問題なさそう。
よって、paramsが正しく受信されていないのでは？
って考えます。

で、erbを見ると、、、
```html
        <label for="date">日付: </label>
        <input type="date" date="date">

        <label for="time">勉強時間: </label>
        <input type="integer" time="time">

        <label for="memo">メモ: </label>
        <textarea name="content" cols=50 rows=10></textarea>
```

日付と勉強時間のinputタグにname属性がありませんね。。。
たぶん、これが原因です！！

メモみたいに、name="content"の様な記述が足りなかったって感じです。

**Comment by nana1111111** [comment]
ご飯食べて子供もお風呂に入れるなどして作業再会。HEPさんの助言により、無事エラー解消！
データベースにデータが記録されたことも確認。最高かよ。。
`inputのnameの記述は、「名前」の情報を入力するボックスだからnameなのではなくて、カラムの名前ってことなのですね！`
このところを勘違いしてたことが原因だった下記に修正すると無事解消。

posts.erb

```
<link rel="stylesheet" href="/css/study.css" type="text/css" > 

<form action="/posts" method="post">
    <div>
        <label for="date">日付: </label>
        <input type="date" name="date">
    </div>
    <div>
        <label for="time">勉強時間: </label>
        <input type="integer" name="time">
    </div>
    <div>
        <label for="memo">メモ: </label>
        <textarea name="content" cols=50 rows=10></textarea>
    </div>

    <input type="submit" value="記録">
</form>

<% @posts.each do |post| %>
    <h1><%= post['date'] %></h1>
    <p><%= post['time'] %></p>
    <p><%= post['content'] %></p>
<% end %>
```

ここで、送信後の画面を用意してなかったので、真っ白の場面で止まるので、再度postsの画面にリダイレクトされるようにするようにしたいと思った。

**Comment by nana1111111** [comment]
＜メモ＞
各ページ上部のバナーと、アイコン画像、アカウント名はlayout.erbで作る方がいいな。
それはログイン、ログアウト機能と一緒に作った方がいいと思った。忘れないようにする。

**Comment by nana1111111** [comment]
マイページを作るため、mypage.erbを作成したものの、下記が不明。

1.app.rbに記述した、各種計算式のルーティングをどうerbに表示させるように書くのか不明。

2.app.rbにSQLの計算構文は記載してみた。が、postがいいのかgetがいいのか不明。
（getはURLにクエリとして載る。POSTはURL内に載らないようにできる、とはわかるものの・・・）

**Comment by nana1111111** [comment]
迷子の様子（2020/6/7時点の記述）

mypage.erb
```
#postで記録した学習ログをタイムライン風に表示したい。
#LIMIT3 にしたい。どこに書けば良い？？

<% @posts.each do |post| %>
    <h2><%= post['date']</h2>
    <p><%= post['time'] </p>
    <p><%= post['content']</p>
<% end %>


#1000時間まであと何時間を表示したい。
<%= @countdown %>
```

**Comment by nana1111111** [comment]
**迷子の様子（2020/6/7時点の記述）**
・計算のルーティングはpostにしてみた
・ルーティング内SQLの構文は、ターミナルで実行してみた。単体では期待通りの計算が実行できた。
・日付の計算が難しい。SQLでどのように書けばいいか不明。

app.erb
post '/countdown' do
    @countdown = client.exec_params(
        "SELECT 1000 - SUM(time) FROM posts").to_a
    return erb :mypage
end

**Comment by nana1111111** [comment]
わかった！！！！！
フォームの画面以外は、htmlファイルを作ってそこに記載してから、app.rbのルーティングでhtmlを表示すればいいのでは？？？？？？

**Comment by nana1111111** [comment]
6/8 講義内で仲西さんに聞いて、めっちゃ解決した！！ふーーーい！

app.rbでmypage.erbになぜ表示できないのか問題は、下記のように習いながらルーティング修正したら表示できた！めっちゃ嬉しい。。

app.rb
```
get '/mypage' do
    @posts = client.exec_params("SELECT * from posts LIMIT 3").to_a
    @countdown = client.exec_params(
        "SELECT SUM(time) FROM posts").to_a
    @totaltime = @countdown[0]["sum"].to_i
    return erb :mypage
end
```
＜解決したこと＞
①凡ミス：get '' doのところ/を忘れていた
②SQLで1000を入れていたが、データがなかった場合の考慮ができてないのでうまく行ってなかった。なので、シンプルにトータルのみのクエリに変更。（1000から引くのはあとで）
③SUMした値が配列で返って来ていたため、erb側で数値で表示できていなかった。なので、変数に代入してオブジェクトにしてから、.to_iした。

**Comment by nana1111111** [comment]
mypage.erb
```
<h1>マイページ</h1>

<%= @totaltime %>

<% @posts.each do |post| %>
    <h2><%= post['date'] %></h2>
    <p><%= post['time'] %></p>
    <p><%= post['content'] %></p>
<% end %>
```

**Comment by nana1111111** [comment]
postで得たデータを、ルーティングでどう計算式を記述して、erbに返すかわかった。
なので、あとは他に計算したいことをSQLでどう書けばいいのかをやっていく。

日付の扱いが難しい。。
**COUNT**と**GROUP　BY**を調べて、下記の計算ができる構文を作る！

```
#dateの日付を同じ日に複数あってもまとめて、Total●日として数字を出したい
#上記が出せれば、SUM(time)の時間でわり、1日平均●時間の計算
#今日のみのSUM(time)
#当月のみのSUM(time）
#1000時間までのカウントダウン（1000-@totaltime?）

```

**Comment by nana1111111** [comment]
①dateの日付を同じ日に複数あってもまとめて、Total●日として数字を出したい
`SELECT sum(time), date FROM posts GROUP BY date;`

**Comment by nana1111111** [comment]
とりあえず、今までの勉強時間をpostして、データベースに必要なデータを溜めていくことからやルことにする。

スプレッドシートでも計算されているので、SQL文がちゃんと書けて、期待値通りの値が返せているか確認できるため。

**Comment by nana1111111** [comment]
＜メモ＞
追加したい機能見つかった。

**①間違ったpostを削除する機能（データベースからも削除する機能になる？）**
┗間違うといちいちSQLで消さないといけない。ユーザーに優しくない。。

**②勉強時間を小数点第一まで入力できるようにしたい。0.5は必要。**
┗データ型を変更する必要があるな。。

**Comment by nana1111111** [comment]
②TOAL日数出せれば、SUM(time)の時間でわり、1日平均●時間の計算
┗これはRuby側で計算できそう。
`@average = @totaltime /（TOTAL日数を変数に代入した変数名）`

**Comment by nana1111111** [comment]
**③今日のみのSUM(time)**
`SELECT sum(time),date FROM posts WHERE date = CURRENT_DATE GROUP BY date;`

**④当月のみのSUM(time）**

**Comment by nana1111111** [comment]
ここまででいったん計算したいSQLはOK。
マイページに表示させるためのルーティングを書いていく。

**Comment by nana1111111** [comment]
YEEEEEEEEEEEEEEEEES!!ルーティングバッチリいけた。計算はOK♡

app.rb（mypageルーティング）
```
get '/mypage' do
    @posts = client.exec_params("SELECT * from posts ORDER BY id DESC LIMIT 5").to_a
    @times = client.exec_params("SELECT SUM(time) FROM posts").to_a
    @totaltime = @times[0]["sum"].to_f
    @days = client.exec_params("SELECT COUNT(distinct date) FROM posts").to_a
    @day_total = @days[0]["count"].to_i
    @average = (@totaltime / @day_total).to_i
    @todaytime = client.exec_params("SELECT sum(time),date FROM posts WHERE date = CURRENT_DATE GROUP BY date").to_a
    @todaytime_total = @todaytime[0]["sum"].to_f
    return erb :mypage
end
```
mypageはあとHTMLとCSSで見た目を整えるだけだ。
（誰かフロントはお洒落な感じにやって欲しい。。あんまり見た目は興味ないかも。。）

**Comment by takanori-matsushita** [comment]
> ログアウトのボタンを押すと、「Sinatra doesn’t know this ditty.」になるので、loginルーティングにリダイレクトしたいがうまくできない

> # ログアウト用ルーティング
delete '/logout' do
    session[:user] = nil
    return redirect '/login'
end

> <form action="/signout" method="post">

フォームのアクションとルーティングが一致していないですね！

**Comment by takanori-matsushita** [comment]
> サインアップの画面で、登録済みのemailアドレスが入力された場合は、loginページへリダイレクトされるようにしたいがうまくいかない。

railsだとバリデーションという機能がありますが、sinatraだと例外処理をしてあげないといけないですね！

```
post '/signup' do
  name = params[:name]
  email = params[:email]
  password = params[:password]
  begin #以下の処理を実行してエラーが帰ってくるようであればrescueで例外処理をする
    client.exec_params("INSERT INTO users (name, email, password) VALUES ($1, $2, $3)", [name, email, password])
  rescue PG::UniqueViolation #例外処理 emailにuniqueを設定しているため、PG::UniqueViolationというエラーが表示されるが、例外処理を記述することで、エラーに対する処理を実行できる
    return redirect '/signup' #サインアップページへリダイレクト
  end
  user = client.exec_params("SELECT * from users WHERE email = $1 AND password = $2 LIMIT 1", [email, password]).to_a.first
  session[:user] = user
  return redirect '/posts'
end
```
確認していないので動くかわかりませんが、こんな感じになると思います。

**Comment by HidetoNakasone** [comment]
①の問題について
> undefined method `[]' for nil:NilClass
このエラー文が意味することは、@todaytime[0]の次に、["sum"]と書いてあるけど、そんなものはしらない。って感じですね。

詳しく回答させてもらうと、
```ruby
client.exec_params("SELECT sum(time),date FROM posts WHERE date = CURRENT_DATE GROUP BY date").to_a
```
これの返却値って、イメージは 
```ruby
[
  {"id" => "1", "time" => "xxxx","sum" => "xxxx", ,,,},
  {"id" => "2", "time" => "xxxx","sum" => "xxxx", ,,,},
  {"id" => "3", "time" => "xxxx","sum" => "xxxx", ,,,}
]
```
ですよね。
`@todaytime_totdal` は、 ↑ に対して `[0]["sum"].to_f` をしているわけですよね。

比嘉さんの想定： 

[0]により
```ruby
{"id" => "1", "time" => "xxxx","sum" => "xxxx", ,,,}
```

そして、["sum"]により 
```ruby
[
  {"id" => "1", "time" => "xxxx","sum" => "xxxx", ,,,},
  {"id" => "2", "time" => "xxxx","sum" => "xxxx", ,,,},
  {"id" => "3", "time" => "xxxx","sum" => "xxxx", ,,,}
]
```

が取り出され、.to_f が実行されて・・・と行った流れ。だと思っていますよね？

でも、もしからたら
```ruby
[
  {"id" => "1", "time" => "xxxx",,,,},
  {"id" => "2", "time" => "xxxx",.,,},
  {"id" => "3", "time" => "xxxx"...,}
]
```

↑の様に、カラム"sum"のデータが上手く取れていないかもしれません。
// ここは想定です。なので、実際にコードを見ないとわかりません。

予測：

```ruby
{"id" => "1", "time" => "xxxx",,,,}
```

これの、["sum"]を出せ！という部分で、たぶんエラーしているのでは？
だって"sum"なんてキーの値は無いから。。。。

確実にどの部分がエラーしているのか動作を見てみないと分からないです。
ただ、確実に言えるのは、エラー文が良く表示されるパターンとして、
その[]の直前の変数がNilである場合が多いです。

つまり、
```ruby
@todaytime_total = @todaytime[0]["sum"].to_f
```ruby
この部分の中で、
`@todaytime[0]` ここがNilの可能性
`@todaytime[0]["sum"]` ここがNilの可能性
この2パターンが考えられます！

ハッシュに対して
```ruby
{}[]
``` 
キーを指定することは可能です。

ただ、
```ruby
Nil[]
```

Nilに対して [] のようなキーを指定されてもRuby的にはそんなの知らないって感じです。

**Comment by nana1111111** [comment]
見た目を整え終わった。なんとか形にはできたと思う。
まだまだ満足はしていないので、今後は下記を追加していきたい。


--------------------------------------------
**【機能】**

- [ ] ①サインアップ時、nilだと登録できないようにする
- [ ] ②サインアップ、時間投稿画面で「入力内容を確認しましたか？」のアラートポップアップ表示
- [ ] ③時間投稿画面で、「記録する」を押して終わったら、「記録が完了しました」のポップアップ表示
- [ ] ④間違ったpostを削除する機能
- [ ] ⑤mypageでグラフを表示（動的に処理して表示が変わるように）

┗月別の計算処理と、グラフにもしたい。。


**【見た目】**

- [ ] ①バナーのレスポンシブ対応
- [ ] ②アイコン画像、アカウント名表示
- [ ] ③全体的にもっとカッコよくしたい

┗強調したい時間とかを目立たせたたり。オシャレに。

**Comment by nana1111111** [comment]
自分で使い倒す！っていうのは大事だと思った。
どうすればもっと使いやすくなるのか、をすごく考えられる。

**Comment by nana1111111** [comment]
todoリストは難しかったので断念！
でも機能としては欲しかったので、GoogleKEEPをリンクするという勉強する身としてやってはいけないことをした感www

このアプリはSinatra制作はここで終。
Railsベンキョしながら、Railsで満足のいく仕上がりにすることにします。　-fin-
